version: '3'
services:
  charabako:
    build: 
      context: ./docker
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app