version: '3'
services:
  app:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${D_ATABASE}
      - MYSQL_USER=${U_SERNAME}
      - MYSQL_PASSWORD=${U_SERPASS}
      - MYSQL_ROOT_PASSWORD=${R_OOTPASS}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  test-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DATA_BASE}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASS}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - TZ=Asia/Tokyo
    ports:
      - '3307:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${U_SERNAME}
      - PMA_PASSWORD=${U_SERPASS}
    depends_on:
      - db