version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: echo "Hello World"
  deploy:
    machine: true
    steps:
      - add_ssh_keys
      - run:
          name: deploy1
          command: |
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd kutulu-character_sheet-backend && \
              git pull origin main && \
              touch .env && \
              cd shell && sh envcreate.sh"
      - run: 
          name: deploy2
          command: |
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd kutulu-character_sheet-backend && \
            docker-compose -f docker-compose.prod.yml down -v && \
            docker-compose -f docker-compose.prod.yml up -d --build"
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main