version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: echo "Hello World"
  deploy:
    machine: true
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd laravel-ci && \
              git pull origin master && \
              docker-compose -f docker-compose.prod.yml down -v && \
              docker-compose -f docker-compose.prod.yml up -d --build"